import '../style.css'
import './pages/authorization/authorization.css'
import './pages/registration/registration.css'
import './pages/home/home.css'
import './pages/404/404.css'
import './pages/500/500.css'